name: Deploy Lambdas

on:
    push:
        branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18"

            # Instalar dependencias y crear ZIPS para cada Lambda
            - name: Build User Lambdas
              run: |
                  cd lambdas/user
                   npm install || true                 # si hay package.json
                   zip -r register.zip register.js node_modules/
                   zip -r confirm.zip confirm.js node_modules/
                   zip -r login.zip login.js node_modules/
                   mv register.zip ../../terraform/
                   mv confirm.zip ../../terraform/
                   mv login.zip ../../terraform/
            - name: Build Product Lambdas
              run: |
                  cd lambdas/product
                  npm install || true                 # si hay package.json
                  zip -r get.zip get.js node_modules/
                  zip -r validate.zip validate.js node_modules/
                  mv get.zip ../../terraform/
                  mv validate.zip ../../terraform/

            # Terraform Init/Plan/Apply
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3

            - name: Terraform Init
              run: terraform init
              working-directory: terraform

            - name: Terraform Apply
              run: terraform apply -auto-approve
              working-directory: terraform
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
