name: Deploy Lambdas

on:
    push:
        branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18"

            # Instalar dependencias y crear ZIPS para cada Lambda
            - name: Build User Lambdas
              run: |
                  cd lambdas/user
                   npm install || true                 # si hay package.json
                   zip -r register.zip register.js auth/ utils/ node_modules/ package.json
                   zip -r confirm.zip confirm.js node_modules/ package.json
                   zip -r login.zip login.js auth/ utils/ node_modules/ package.json
                   mv register.zip ../../terraform/
                   mv confirm.zip ../../terraform/
                   mv login.zip ../../terraform/
            - name: Build Product Lambdas
              run: |
                  cd lambdas/product
                  npm install || true                 # si hay package.json
                  zip -r get.zip get.js node_modules/ package.json
                  zip -r validate.zip validate.js node_modules/ package.json
                  zip -r post.zip post.js middleware/ node_modules/ package.json
                  mv get.zip ../../terraform/
                  mv validate.zip ../../terraform/
                  mv post.zip ../../terraform/

            - name: Terraform Import existing resources
              run: |
                terraform init
                terraform import aws_dynamodb_table.users users || true
                terraform import aws_dynamodb_table.products products || true
                terraform import aws_dynamodb_table.cart cart || true
                terraform import aws_iam_role.lambda-exec-role lambda-exec-role || true
              working-directory: terraform
              env:
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

            - name: List files in terraform directory
              run: ls -l
              working-directory: terraform

              # Terraform Init/Plan/Apply
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3

            - name: Terraform Init
              run: terraform init
              working-directory: terraform

            - name: Terraform Apply
              run: terraform apply -auto-approve
              working-directory: terraform
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
